### PR TITLE
Install all the build libraries and update the pkgconfig

### PR DESCRIPTION
**Pull request by andreapiacentini**
`make install` now installs all the header and fortran module files and all the needed libraries, including the externally built hwloc and spdlog.
pkgconfig information updated for `quo-vadis` (C) and `quo-vadisf` (F90) packages. The mpi libraries are conditionally included, following the MPI activation toggle at cmake.  

As an example, provided the `PKG_CONFIG_PATH` includes `${QV_INSTALL}/lib/pkgconfig`, the compilation of a fortran test 
is simply
```
mpif90 `pkg-config --cflags quo-vadisf` -g -O3 -fopenmp -c test-mpi-qvfort.f90
mpif90 -g -O3 -fopenmp test-mpi-qvfort.o -o test-mpi-qvfort `pkg-config --libs quo-vadisf`
```
or with the intel compiler
```
mpiifort `pkg-config --cflags quo-vadisf` -g -O3 -qopenmp -c test-mpi-qvfort.f90
mpiifort -g -O3 -qopenmp test-mpi-qvfort.o -o test-mpi-qvfort `pkg-config --libs quo-vadisf`
```

### CODE REVIEW

**Comment by samuelkgutierrez** [comment]
Hi, @andreapiacentini. Thank you for sharing this and thank you for your patience! Can you please give 0b0aeb24401d3dff66662986d0bb690c644f16f6 a try to see if it works for you? Static libraries in CMake are apparently a pain, so I'm giving up on that for now.

**Comment by samuelkgutierrez** [comment]
This may be useful information. Here is an example build invocation to build a Fortran code:
`export QV_HOME=/home/samuel/tmp/quo-vadis && mpifort -I$QV_HOME/lib test-mpi-qvfort.f90 -L$QV_HOME/lib -o mpi-qvfort -lquo_vadis_mpif`

**Comment by andreapiacentini** [comment]
Nope,
at compile the 
```
mpiifort -O3 -qopenmp -I$QV_INSTALL/lib -c test-mpi-qvfort.f90
test-mpi-qvfort.f90(16): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [QUO_VADISF]
```
we lack the `quo_vadisf.mod` file in `lib` (moreover I always feel uncomfortable with modules in lib rather than in include)

Copied it in by hand, link isn't happy either
```
mpiifort -O3 -qopenmp -L$QV_INSTALL/lib -o test-mpi-qvfort test-mpi-qvfort.o -l quo_vadis_mpif
//home/globc/andrea/INSTALL/quo-vadis/lib/libquo-vadis-mpi.so: undefined reference to 'quo_vadis_internal_hwloc_get_proc_cpubind'
```

I tried postponing the shared object ilnk with an embedded path
```
mpiifort -O3 -qopenmp -Wl,-rpath=$QV_INSTALL/lib -L$QV_INSTALL/lib -o test-mpi-qvfort test-mpi-qvfort.o -lquo_vadis_mpif
```
But I just pushed the problem at run time:
```
${QV_INSTALL}/bin/quo-vadisd &
mpirun -np 2 test-mpi-qvfort
test-mpi-qvfort: symbol lookup error: /home/globc/andrea/INSTALL/quo-vadis/lib/libquo-vadis-mpi.so: undefined symbol: quo_vadis_internal_hwloc_topology_init
test-mpi-qvfort: symbol lookup error: /home/globc/andrea/INSTALL/quo-vadis/lib/libquo-vadis-mpi.so: undefined symbol: quo_vadis_internal_hwloc_topology_init
```

For the moment. my pkg-config solution with static libraries seems handier.
Why not simply use `ar` on the component `.a` at install time and come out with a single self contained static library ?

**Comment by andreapiacentini** [comment]
I was pretty much sure that having added the `-Wl,-rpath=$QV_INSTALL/lib` at link I could have avoided the `LD_LIBRARY_PATH`
It's late now here, tomorrow I'll check the nuances. With the extended `LD_LIBRARY_PATH` it seems to work.
I'll do everything again from scratch tomorrow.
Are you going to generate separate pkgconfig files for C and Fortran ?
In the meantime
```
ldd libquo_vadis_mpif.so
        linux-vdso.so.1 (0x00007ffced5f7000)
        libquo-vadis-mpi.so => /home/globc/andrea/INSTALL/quo-vadis/lib/libquo-vadis-mpi.so (0x000014b58eba7000)
        libmpifort.so.12 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/lib/libmpifort.so.12 (0x000014b58e7e9000)
        libmpi.so.12 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/lib/release/libmpi.so.12 (0x000014b58d470000)
        libdl.so.2 => /lib64/libdl.so.2 (0x000014b58d26c000)
        librt.so.1 => /lib64/librt.so.1 (0x000014b58d064000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000014b58ce45000)
        libhwloc.so.15 => /home/globc/andrea/INSTALL/quo-vadis/lib/libhwloc.so.15 (0x000014b58cbcc000)
        libpciaccess.so.0 => /lib64/libpciaccess.so.0 (0x000014b58c9c3000)
        libzmq.so.5 => /lib64/libzmq.so.5 (0x000014b58c74f000)
        libifport.so.5 => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libifport.so.5 (0x000014b58c521000)
        libifcoremt.so.5 => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libifcoremt.so.5 (0x000014b58f0ef000)
        libimf.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libimf.so (0x000014b58be99000)
        libsvml.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libsvml.so (0x000014b58a39c000)
        libm.so.6 => /lib64/libm.so.6 (0x000014b58a086000)
        libintlc.so.5 => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x000014b589e0e000)
        libc.so.6 => /lib64/libc.so.6 (0x000014b589a39000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x000014b589822000)
        libirng.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libirng.so (0x000014b5894b8000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x000014b58912f000)
        /lib64/ld-linux-x86-64.so.2 (0x000014b58f0b5000)
        libfabric.so.1 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/libfabric/lib/libfabric.so.1 (0x000014b588ee9000)
        libpgm-5.2.so.0 => /lib64/libpgm-5.2.so.0 (0x000014b588c9d000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x000014b588a50000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x000014b588769000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x000014b588536000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x000014b588332000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x000014b588123000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x000014b587f1f000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x000014b587d05000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x000014b587add000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x000014b58786b000)
```
and
```
ldd libquo-vadis-mpi.so
        linux-vdso.so.1 (0x00007ffdaf56b000)
        libmpifort.so.12 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/lib/libmpifort.so.12 (0x00001529fc4e8000)
        libmpi.so.12 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/lib/release/libmpi.so.12 (0x00001529fb16f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00001529faf6b000)
        librt.so.1 => /lib64/librt.so.1 (0x00001529fad63000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00001529fab44000)
        libhwloc.so.15 => /home/globc/andrea/INSTALL/quo-vadis/lib/libhwloc.so.15 (0x00001529fa8cb000)
        libpciaccess.so.0 => /lib64/libpciaccess.so.0 (0x00001529fa6c2000)
        libzmq.so.5 => /lib64/libzmq.so.5 (0x00001529fa44e000)
        libimf.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libimf.so (0x00001529f9dc6000)
        libsvml.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libsvml.so (0x00001529f82c9000)
        libirng.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libirng.so (0x00001529f7f5f000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00001529f7bd6000)
        libm.so.6 => /lib64/libm.so.6 (0x00001529f78c0000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00001529f76a9000)
        libintlc.so.5 => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00001529f7431000)
        libc.so.6 => /lib64/libc.so.6 (0x00001529f705c000)
        /lib64/ld-linux-x86-64.so.2 (0x00001529fcbb0000)
        libfabric.so.1 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/libfabric/lib/libfabric.so.1 (0x00001529f6e16000)
        libpgm-5.2.so.0 => /lib64/libpgm-5.2.so.0 (0x00001529f6bca000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00001529f697d000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00001529f6696000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00001529f6463000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00001529f625f000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00001529f6050000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00001529f5e4c000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00001529f5c32000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00001529f5a0a000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00001529f5798000)
```
Did you choose on purpose to use underscores in `libquo_vadis_mpif.so` and dashes in `libquo-vadis-mpi.so` ?

**Comment by samuelkgutierrez** [comment]
> I was pretty much sure that having added the `-Wl,-rpath=$QV_INSTALL/lib` at link I could have avoided the `LD_LIBRARY_PATH` It's late now here, tomorrow I'll check the nuances. With the extended `LD_LIBRARY_PATH` it seems to work. I'll do everything again from scratch tomorrow. Are you going to generate separate pkgconfig files for C and Fortran ?

Yes, that is the plan. I'll open an issue to track this. Good night and thank you again.

> In the meantime
> 
> ```
> ldd libquo_vadis_mpif.so
>         linux-vdso.so.1 (0x00007ffced5f7000)
>         libquo-vadis-mpi.so => /home/globc/andrea/INSTALL/quo-vadis/lib/libquo-vadis-mpi.so (0x000014b58eba7000)
>         libmpifort.so.12 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/lib/libmpifort.so.12 (0x000014b58e7e9000)
>         libmpi.so.12 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/lib/release/libmpi.so.12 (0x000014b58d470000)
>         libdl.so.2 => /lib64/libdl.so.2 (0x000014b58d26c000)
>         librt.so.1 => /lib64/librt.so.1 (0x000014b58d064000)
>         libpthread.so.0 => /lib64/libpthread.so.0 (0x000014b58ce45000)
>         libhwloc.so.15 => /home/globc/andrea/INSTALL/quo-vadis/lib/libhwloc.so.15 (0x000014b58cbcc000)
>         libpciaccess.so.0 => /lib64/libpciaccess.so.0 (0x000014b58c9c3000)
>         libzmq.so.5 => /lib64/libzmq.so.5 (0x000014b58c74f000)
>         libifport.so.5 => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libifport.so.5 (0x000014b58c521000)
>         libifcoremt.so.5 => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libifcoremt.so.5 (0x000014b58f0ef000)
>         libimf.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libimf.so (0x000014b58be99000)
>         libsvml.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libsvml.so (0x000014b58a39c000)
>         libm.so.6 => /lib64/libm.so.6 (0x000014b58a086000)
>         libintlc.so.5 => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x000014b589e0e000)
>         libc.so.6 => /lib64/libc.so.6 (0x000014b589a39000)
>         libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x000014b589822000)
>         libirng.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libirng.so (0x000014b5894b8000)
>         libstdc++.so.6 => /lib64/libstdc++.so.6 (0x000014b58912f000)
>         /lib64/ld-linux-x86-64.so.2 (0x000014b58f0b5000)
>         libfabric.so.1 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/libfabric/lib/libfabric.so.1 (0x000014b588ee9000)
>         libpgm-5.2.so.0 => /lib64/libpgm-5.2.so.0 (0x000014b588c9d000)
>         libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x000014b588a50000)
>         libkrb5.so.3 => /lib64/libkrb5.so.3 (0x000014b588769000)
>         libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x000014b588536000)
>         libcom_err.so.2 => /lib64/libcom_err.so.2 (0x000014b588332000)
>         libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x000014b588123000)
>         libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x000014b587f1f000)
>         libresolv.so.2 => /lib64/libresolv.so.2 (0x000014b587d05000)
>         libselinux.so.1 => /lib64/libselinux.so.1 (0x000014b587add000)
>         libpcre.so.1 => /lib64/libpcre.so.1 (0x000014b58786b000)
> ```
> 
> and
> 
> ```
> ldd libquo-vadis-mpi.so
>         linux-vdso.so.1 (0x00007ffdaf56b000)
>         libmpifort.so.12 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/lib/libmpifort.so.12 (0x00001529fc4e8000)
>         libmpi.so.12 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/lib/release/libmpi.so.12 (0x00001529fb16f000)
>         libdl.so.2 => /lib64/libdl.so.2 (0x00001529faf6b000)
>         librt.so.1 => /lib64/librt.so.1 (0x00001529fad63000)
>         libpthread.so.0 => /lib64/libpthread.so.0 (0x00001529fab44000)
>         libhwloc.so.15 => /home/globc/andrea/INSTALL/quo-vadis/lib/libhwloc.so.15 (0x00001529fa8cb000)
>         libpciaccess.so.0 => /lib64/libpciaccess.so.0 (0x00001529fa6c2000)
>         libzmq.so.5 => /lib64/libzmq.so.5 (0x00001529fa44e000)
>         libimf.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libimf.so (0x00001529f9dc6000)
>         libsvml.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libsvml.so (0x00001529f82c9000)
>         libirng.so => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libirng.so (0x00001529f7f5f000)
>         libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00001529f7bd6000)
>         libm.so.6 => /lib64/libm.so.6 (0x00001529f78c0000)
>         libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00001529f76a9000)
>         libintlc.so.5 => /scratch/root/opt/intel/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00001529f7431000)
>         libc.so.6 => /lib64/libc.so.6 (0x00001529f705c000)
>         /lib64/ld-linux-x86-64.so.2 (0x00001529fcbb0000)
>         libfabric.so.1 => /scratch/root/opt/intel/oneapi/mpi/2021.1.1/libfabric/lib/libfabric.so.1 (0x00001529f6e16000)
>         libpgm-5.2.so.0 => /lib64/libpgm-5.2.so.0 (0x00001529f6bca000)
>         libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00001529f697d000)
>         libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00001529f6696000)
>         libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00001529f6463000)
>         libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00001529f625f000)
>         libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00001529f6050000)
>         libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00001529f5e4c000)
>         libresolv.so.2 => /lib64/libresolv.so.2 (0x00001529f5c32000)
>         libselinux.so.1 => /lib64/libselinux.so.1 (0x00001529f5a0a000)
>         libpcre.so.1 => /lib64/libpcre.so.1 (0x00001529f5798000)
> ```

These both look correct. Thank you.

> 
> Did you choose on purpose to use underscores in `libquo_vadis_mpif.so` and dashes in `libquo-vadis-mpi.so` ?

It's a byproduct of how CMake automatically generates library names associated with a particular target. I don't like the inconsistency either. I'll see if I can address this.

**Comment by samuelkgutierrez** [comment]
> Did you choose on purpose to use underscores in `libquo_vadis_mpif.so` and dashes in `libquo-vadis-mpi.so` ?

This should be fixed in ca9871171457ed1d0a206c0d71339d11781ed62c.

**Comment by andreapiacentini** [comment]
I unravelled the `-Wl,-rpath` vs `LD_LIBRARY_PATH` issue.
The former used at link time replace the second only if it is merely the executable which depends on self contained shared libraries.
If a shared library depends on another shared library, unless `-Wl,-rpath` is used also at the link command creating the library, the `LD_LIBRARY_PATH` has to point at the indirect dependency path.
Once understood, ok, I dropped the `-Wl,-rpath` and extended the `LD_LIBRARY_PATH` in my settings.
I think, anyway, it has to be mentioned in the doc.

**Pull request closed without merging**
