### PR TITLE
Basic infrastructure for thread support

### PR DESCRIPTION
**Pull request by GuillaumeMercier**
- This should be put in a new branch, NOT in master
- Pthread version is not yet working
- OpenMP version is partially working
- Mixing threads and processes needs some more work (e.g Common Group ID values)
- Support for binding thread and/or processes should be OK, but I'm not sure that the interface is alright.

### CODE REVIEW

**Comment by samuelkgutierrez** [comment]
Hi, @GuillaumeMercier. Fantastic! Can you push these changes into a new branch here yourself? If not, then I need to modify your access permissions.

**Comment by GuillaumeMercier** [comment]
Hi @samuelkgutierrez, I just created said branch.

**Comment by samuelkgutierrez** [comment]
Perfect! I like what I'm seeing so far. Thank you.

**Comment by GuillaumeMercier** [comment]
Hold your horses, Cowboy, otherwise you'll get disappointed I think.
Anyway, I think that I know have a quite good understanding of your whole architecture so I think I'll be more efficient from now on.
Stay tuned.

**Comment by samuelkgutierrez** [comment]
@GuillaumeMercier I have a question: how about we checkpoint your threading work into master? So long as it doesn't break anything else, why not? The reason I ask is because I'm working on a new splitting algorithm and don't want us to diverge too much.

**Comment by GuillaumeMercier** [comment]
> @GuillaumeMercier I have a question: how about we checkpoint your threading work into master? So long as it doesn't break anything else, why not? The reason I ask is because I'm working on implementing a new splitting algorithm and don't want us to diverge too much.

Well, Im' not sure that the road I took is the best one.  But if you think that it's ok (I mean introducing the task type and modifing some of the functions prototypes) we can go ahead. Would it be possible to just wait for a couple of days? I'll be working on this 
and if I realize that something is wrong, we can avoid to backtrack. 

What kind of algorithm are you working on?

**Comment by samuelkgutierrez** [comment]
Nothing that you've done seems unreasonable to me, but I'm happy to wait until you feel comfortable. Please just let me know. Backtracking is perfectly fine, too.

I'm working on the *affinity preserving* splitting algorithm. All it does is group and split tasks based on the callers' requests and the tasks' current affinities. I'm reusing the algorithm that's used in Quo, as it has proven robust. We'll see if that's a good idea.

**Comment by GuillaumeMercier** [comment]
OK, let's wait a couple of days then.
Are you introducing a new routine or modifying an existing one?

**Comment by samuelkgutierrez** [comment]
I'm implementing the unhandled case [here](https://github.com/hpc/quo-vadis/blob/master/src/qvi-scope.cc#L581).

**Comment by GuillaumeMercier** [comment]
Ok, thanks!

**Comment by GuillaumeMercier** [comment]
Question to @samuelkgutierrez: instead of introducing a new parameter (task type) to a bunh of functions, how about replacing the pid_t type argument with  a struct like:
```
struct task_id {
 take_type_t type;
 pid_t who;
}
```

**Comment by samuelkgutierrez** [comment]
I like it!

**Comment by GuillaumeMercier** [comment]
Ok, fine, let's do this then.

**Comment by GuillaumeMercier** [comment]
@samuelkgutierrez : I tried to replace the two variables with a struct. I'm not sure about the names and you might want to change the location of some data structures definitions. I'll work on the pthread version tomorrow (well, technically in a couple of hours since it's 4 am now). With OpenMP, it's easy to get a rank number and a group size, but it's way more challenging with direct calls to the pthread library. I'll probably need to introduce some specific functions (e.g. a kind of group register one).
My next move is to work on the policies support because it's what I was supposed to do in the first place.

**Comment by samuelkgutierrez** [comment]
Sounds great, @GuillaumeMercier. Thank you and please get some rest!

**Comment by GuillaumeMercier** [comment]
Well, I know that I would not manage to get some sleep until everything compiles. It took more time than expected :)

**Comment by GuillaumeMercier** [comment]
By all means, take a look to what I pushed and modify at will.

**Comment by samuelkgutierrez** [comment]
Hi @GuillaumeMercier. I pushed some minor updates and am done for the night. Hopefully I didn't break anything for you.

**Comment by GuillaumeMercier** [comment]
Hi @samuelkgutierrez. No it's fine thank you for your cleanup. It's exactly what I wanted, especially in the pack/unpack routines
because the whole logic is sometimes fuzzy for me. For instance, why sending  (almost) everything as ints?

**Comment by GuillaumeMercier** [comment]
@samuelkgutierrez : if what is in the thread-support branch is ok with you, you can go ahead and merge/apply to the master branch.

**Comment by samuelkgutierrez** [comment]
Hi @GuillaumeMercier,

Thank you very much! I've merged your code, but I think the email I used isn't associated with your GitHub account. I tried to fix this, but couldn't. We can discuss this offline.

I use ints for enums to avoid problems with the potentially variable sizes of enums in C++.

**Comment by GuillaumeMercier** [comment]
Ah yes. The address you used is the one I use to sign my commits but for some reason, I never associated it with my account. It's done now and might solve any issue you had.

**Comment by GuillaumeMercier** [comment]
Oh yes. I messed up with my repo and I was thinking of recloning anyway. You mean delete my current fork and recreating one from the updated version you're working on?

**Comment by samuelkgutierrez** [comment]
I'm going to keep your fork and just rewrite history to cleanup the mess I made merging it (twice!). I'll let you know when I'm done. Fingers crossed!

**Comment by GuillaumeMercier** [comment]
OK, good luck!

**Comment by samuelkgutierrez** [comment]
Okay, I'm done. Yikes! Please reclone and see if your changes made it okay to `master`. Thank you for your patience, @GuillaumeMercier.

**Pull request closed without merging**
