### PR TITLE
Thread layout interface

### PR DESCRIPTION
**Pull request by GuillaumeMercier**
A first draft of the thread layout interface to support hybrid programs.

### CODE REVIEW

**Comment by samuelkgutierrez** [comment]
Hi, @GuillaumeMercier. Can you please fix the style check failures (whitespace)? Also, can you squash all the intermediate commits into a single commit?

**Comment by GuillaumeMercier** [comment]
Will do.

**Review by samuelkgutierrez — APPROVED** [review]
Looking good, @GuillaumeMercier. Thank you.

**Comment by GuillaumeMercier** [comment]
@samuelkgutierrez : I had to force-push a zillion times but it's ok now.

**Pull request merged**
